from pathlib import Path
from typing import Protocol


class ObjectStorage(Protocol):
    async def put(self, object_key: str, source: Path, content_type: str) -> None: ...

    async def get(self, object_key: str) -> bytes: ...

    async def delete(self, object_key: str) -> None: ...

    async def exists(self, object_key: str) -> bool: ...

    async def ready(self) -> bool: ...
