from enum import StrEnum


class CaseStatus(StrEnum):
    CREATED = "CREATED"
    UPLOADING = "UPLOADING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_RISK_REVIEW = "WAITING_RISK_REVIEW"
    WAITING_REPORT_REVIEW = "WAITING_REPORT_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class EvidenceSourceType(StrEnum):
    EMAIL = "EMAIL"
    BANK = "BANK"
    CUSTOMS = "CUSTOMS"
    OTHER = "OTHER"


class DocumentType(StrEnum):
    UNKNOWN = "UNKNOWN"
    EMAIL = "EMAIL"
    PDF = "PDF"
    EXCEL = "EXCEL"
    CSV = "CSV"
    WORD = "WORD"
    IMAGE = "IMAGE"
    TEXT = "TEXT"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    EVIDENCE_UPLOAD_STARTED = "EVIDENCE_UPLOAD_STARTED"
    EVIDENCE_HASHED = "EVIDENCE_HASHED"
    EVIDENCE_STORED = "EVIDENCE_STORED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_UPLOAD_FAILED = "EVIDENCE_UPLOAD_FAILED"
    EVIDENCE_DELETED = "EVIDENCE_DELETED"
    AUDIT_CHAIN_VERIFIED = "AUDIT_CHAIN_VERIFIED"
