from enum import StrEnum


class CaseStatus(StrEnum):
    CREATED = "CREATED"
    UPLOADING = "UPLOADING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_RISK_REVIEW = "WAITING_RISK_REVIEW"
    WAITING_REPORT_REVIEW = "WAITING_REPORT_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class EvidenceSourceType(StrEnum):
    EMAIL = "EMAIL"
    BANK = "BANK"
    CUSTOMS = "CUSTOMS"
    OTHER = "OTHER"


class DocumentType(StrEnum):
    UNKNOWN = "UNKNOWN"
    EMAIL = "EMAIL"
    PDF = "PDF"
    EXCEL = "EXCEL"
    CSV = "CSV"
    WORD = "WORD"
    IMAGE = "IMAGE"
    TEXT = "TEXT"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    EVIDENCE_UPLOAD_STARTED = "EVIDENCE_UPLOAD_STARTED"
    EVIDENCE_HASHED = "EVIDENCE_HASHED"
    EVIDENCE_STORED = "EVIDENCE_STORED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_UPLOAD_FAILED = "EVIDENCE_UPLOAD_FAILED"
    EVIDENCE_DELETED = "EVIDENCE_DELETED"
    AUDIT_CHAIN_VERIFIED = "AUDIT_CHAIN_VERIFIED"


class WorkflowRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_REVIEW = "WAITING_REVIEW"
    WAITING_EVIDENCE = "WAITING_EVIDENCE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class WorkflowEventType(StrEnum):
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    REVIEW_DECIDED = "REVIEW_DECIDED"
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_RETRYING = "WORKFLOW_RETRYING"
    WORKFLOW_TIMED_OUT = "WORKFLOW_TIMED_OUT"


class ReviewTaskStatus(StrEnum):
    PENDING = "PENDING"
    DECIDED = "DECIDED"
    CANCELLED = "CANCELLED"


class ArtifactStatus(StrEnum):
    CREATED = "CREATED"
    SUPERSEDED = "SUPERSEDED"


class EvidenceProcessingStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    UNSUPPORTED = "UNSUPPORTED"
    OCR_REQUIRED = "OCR_REQUIRED"
    FAILED = "FAILED"


class NormalizedDocumentStatus(StrEnum):
    READY = "READY"
    UNSUPPORTED = "UNSUPPORTED"
    OCR_REQUIRED = "OCR_REQUIRED"
